http {

    geo $region {
        default us_east;

        # IP ranges go here
        # North American ranges → us_east
        # European ranges → europe
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$region;
        }
    }
}