spring.application.name=sandinify

#SQL SERVER
spring.datasource.url=jdbc:postgresql://localhost:5432/sandinify
spring.datasource.username=postgres
spring.datasource.password=#sample#project999

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true